version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: microservice-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - micro-net
      # åœ¨ sqlserver æœåŠ¡ä¸­æ·»åŠ äº† volumes æ˜ å°„ï¼Œå°† sql_data æŒ‚è½½åˆ°å®¹å™¨å†…çš„ /var/opt/mssql
    volumes:
      - sql_data:/var/opt/mssql
  identity-api:
    build:
      context: .
      dockerfile: Microservice.IdentityServer/Dockerfile
    container_name: identity-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # ğŸ‘‡ å¼ºåˆ¶ç›‘å¬ HTTP ç«¯å£
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MicroService_IdentityDb;User Id=sa;Password=MyStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver
    networks:
      - micro-net

  product-api:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    container_name: product-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # ğŸ‘‡ å¼ºåˆ¶ç›‘å¬ HTTP ç«¯å£
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MicroService_ProductDb;User Id=sa;Password=MyStrong!Passw0rd;TrustServerCertificate=True;
      - JwtSettings__SecretKey=ThisIsASecretKeyForMyMicroserviceProject_MustBeLongEnough
      - JwtSettings__Issuer=MyMicroserviceApp
      - JwtSettings__Audience=MyMicroserviceClient
    ports:
      - "5002:8080"
    depends_on:
      - sqlserver
    networks:
      - micro-net

  gateway-api:
    build:
      context: .
      dockerfile: Microservice.Gateways/Dockerfile
    container_name: gateway-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # ğŸ‘‡ å¼ºåˆ¶ç›‘å¬ HTTP ç«¯å£
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5000:8080"
    depends_on:
      - identity-api
      - product-api
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
#volumes å£°æ˜
volumes:
  sql_data: